defaults: &defaults
  redis:
    cache_store: 'redis://localhost:6379/0/cache_store'
    meta_store: 'redis://localhost:6379/1/meta_store'
    entity_store: 'redis://localhost:6379/1/entity_store'
  sms_captcha:
    length: 6
    range: <%= (0..9).to_a %>
  yooyoung:
    name: 悠漾旅行
    homepage: "www.yooyoung.cn"
    service_phone: "010-58070160"
    service_phone_with_space: "010 - 58070160"
    domain: '.yooyoung.cn'
    weibo_url: 'http://weibo.com/u/5454372745'
  china_country_code: 1
  mailer:
    from: 'no-reply@yooyoung.cn'
    bcc: 'trades_notification@yooyoung.cn'
  sms:
    switch: false
    username: "yooyoung.cn"
    password: "yooyoung0120"
    sms_limit: 5
  home:
    banner: <%= %w[9 5 3] %>
    section: <%= %w[2 7 4 3 9 5] %>
  payment:
    alipay:
      gateway: https://mapi.alipay.com/gateway.do
      account: 2088811054686737
      email: 2495363351@qq.com
      key: kvvq2f6ks5siat7ecvqka8wu3z5b8x8i

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  sms:
    switch: true
  sms_captcha:
    length: 6
    range: <%= (0..9).to_a %>
