defaults: &defaults
  redis:
    cache_store: 'redis://localhost:6379/0/cache_store'
    meta_store: 'redis://localhost:6379/1/meta_store'
    entity_store: 'redis://localhost:6379/1/entity_store'
  sms_captcha:
    length: 6
    range: <%= (0..9).to_a %>
    switch: false
  yooyoung:
    service_phone: "010-58070160"
    service_phone_with_space: "010 - 58070160"
  china_country_code: 1
  sms:
    username: "yooyoung.cn"
    password: "yooyoung0120"
    sms_limit: 5

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  sms_captcha:
    length: 6
    range: <%= (0..9).to_a %>
    switch: true
