defaults: &defaults
  redis:
    cache_store: 'redis://localhost:6379/0/cache_store'
    meta_store: 'redis://localhost:6379/1/meta_store'
    entity_store: 'redis://localhost:6379/1/entity_store'
  sms_captcha:
    length: 6
    range: <%= (0..9).to_a %>
    time: 60
  yooyoung:
    name: 悠漾旅行
    homepage: "www.yooyoung.cn"
    service_phone: "010-58070160"
    service_phone_with_space: "010 - 58070160"
    service_time: '客服时间 10:00 - 22:00'
    domain: '.yooyoung.cn'
    weibo_url: 'http://weibo.com/u/5454372745'
    weixin_url: 'http://mp.weixin.qq.com/s?__biz=MzA3MDM0Njc4Mg==&mid=204746563&idx=1&sn=8ce1651074be83106c61a26bf9c80572#rd'
  china_country_code: 1
  mailer:
    from: 'no-reply@yooyoung.cn'
    bcc: 'trades_notification@yooyoung.cn'
  sms:
    switch: false
    username: "yooyoung.cn"
    password: "yooyoung0120"
    sms_limit: 5
  home:
    banner: <%= %w[30 20 21] %>
    section: <%= %w[28 27 12 22 11 30 24 20 21 19 7 18] %>
  payment:
    alipay:
      gateway: https://mapi.alipay.com/gateway.do
      account: 2088811054686737
      email: 2495363351@qq.com
      key: kvvq2f6ks5siat7ecvqka8wu3z5b8x8i
  seo:
    title: "悠漾，悠选酒店套餐，打造非凡旅行，臻选全球奢华酒店预订，私人定制，酒店套餐，度假旅行，蜜月旅行预订"
    description: "悠漾，悠选酒店套餐，打造非凡旅行，最贴心的奢华酒店预订平台，全程服务，品质保证。精选全球奢华酒店预订，第一家专注酒店套餐设计、专注度假游及预订的在线平台。"
    keywords: <%= %w[悠漾 yooyoung 悠漾旅行 奢华酒店预订 臻选酒店预订 酒店套餐预订 私人定制 度假游 蜜月游].join(',') %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  sms:
    switch: true
    username: "yooyoung.cn"
    password: "yooyoung0120"
    sms_limit: 5
